const Products = [
  {
    "id": 65,
    "name": "ARGENTINIAN BEEF FILET SOUP",
    "description": "",
    "price": 289500.0,
    "promotedPrice": 269500.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 0,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 66,
    "name": "LOBSTER AND CRAB MEAT SOUP",
    "description": "",
    "price": 289400.0,
    "promotedPrice": 259400.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 0,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 66,
    "name": "LOBSTER AND CRAB MEAT SOUP",
    "description": "",
    "price": 290000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 0,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 67,
    "name": "BEEF EMPANADA",
    "description": "",
    "price": 179300.0,
    "promotedPrice": 139300.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 68,
    "name": "CHORIZO BEEF",
    "description": "Homemade argentinian spiced sausage",
    "price": 209200.0,
    "promotedPrice": 159200.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 69,
    "name": "SALCHICHA",
    "description": "Homemade argentinian spicy sausage",
    "price": 209100.0,
    "promotedPrice": 149100.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 70,
    "name": "PROVOLETA",
    "description": "Grilled provolone cheese, tomato with a hint of oregano",
    "price": 280000.0,
    "promotedPrice": -1.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 71,
    "name": "TACOS",
    "description": "Lean homemade minced beef, crispy taco shells, avocado, tomato, chives, coriander (2PCS PER SERVING)",
    "price": 289900.0,
    "promotedPrice": 209900.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 88,
    "name": "FILET STEAK",
    "description": "",
    "price": 1936200.0,
    "promotedPrice": 1866200.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/el-gaucho-argentinian-steakhouse-restaurant-wagyu-tomahawk-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 213,
    "name": "NEW YORK STRIPLOIN",
    "description": "The USDA Prime is the highest grade of beef in the USA and properly aged in our cold storage for additional 21 to 28 days to fully develop the flavour and tenderness for that melt in your mouth and consistent quality experience. Taken from the smaller end of the tenderloin and located between the sirloin and rib, hand-cut and hand-trimmed by the El Gaucho butchers, the filet steak is a feast for the eye and the mouth. The Castello D’Albola Chianti Classico DOCG 2011 from Tuscany pairs nicely with a filet. It is firm and taut, with a core of cherry and berry flavors, accented by underbrush tobacco and iron notes, balanced with a mineral aftertaste. Perfect for dishes of the traditional Chianti cuisine, as well as for grilled meats and mature cheeses.",
    "price": 497200.0,
    "promotedPrice": 437200.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/El-Gaucho-Argentinian-Steakhouse-Restaurant-Filet-USDA-Prime-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 244,
    "name": "Add On - Foie Gras",
    "description": "The USDA Prime is the highest grade of beef in the USA and properly aged in our cold storage for additional 21 to 28 days to fully develop the flavour and tenderness for that melt in your mouth and consistent quality experience. Taken from the smaller end of the tenderloin and located between the sirloin and rib, hand-cut and hand-trimmed by the El Gaucho butchers, the filet steak is a feast for the eye and the mouth. The Castello D’Albola Chianti Classico DOCG 2011 from Tuscany pairs nicely with a filet. It is firm and taut, with a core of cherry and berry flavors, accented by underbrush tobacco and iron notes, balanced with a mineral aftertaste. Perfect for dishes of the traditional Chianti cuisine, as well as for grilled meats and mature cheeses.",
    "price": 622100.0,
    "promotedPrice": 612100.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/El-Gaucho-Argentinian-Steakhouse-Restaurant-Filet-Platinum-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 8,
    "additions": [],
    "areaId": 8,

  },
  {
    "id": 28,
    "name": "taittinger brut reserve",
    "description": "Brut Réserve Taittinger is one of the last great Champagne Houses to remain independent and is owned and actively managed by the family named on the label. The family are guardians of Taittinger’s style quality and integrity. The hallmark of their fine Champagnes is the high proportion of Chardonnay used in their winemaking which is key, in the Champagne region, for producing wines of great elegance and finesse. Additionally, with its vineyard ownership of 288 ha (one of the largest in Champagne}, Taittinger can guarantee a flawless signature, and wines heralded worldwide for their consistent quality. Our signature cuvée, Taittinger Brut Réserve, is assembled from more than 35 crus and incorporates 40% Chardonnay – this high level is seldom offered in a non-vintage Champagne. Distinguished by a delicate nose marked by subtle brioche notes, it has a palate of considerable depth and balance with hints of honey and fresh fruit with a long, fresh finish.",
    "price": 2099200.0,
    "promotedPrice": 2089200.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/73-MARCHESI-ANTINORI-“SOLAIA”-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 55,
    "name": "krug grande cuvee",
    "description": "Behind every precious drop of Krug stands the dream of a visionary. One man who, long before others, understood that the essence of Champagne is pleasure. So, over 170 years ago, Joseph Krug broke with convention to follow his vision. To create the most generous expression of Champagne every year, regardless of climatic unpredictability.Joseph’s bold experiment proved a triumph and he succeeded in creating Champagne like never before. And like no other Champagne House since. To this day, the House of Krug lives and breathes his enduring philosophy, creating only prestige Champagnes since 1843. Deep golden colour and fine, vivacious bubbles, predicting fullness and elegance. Aromas of flowers in bloom, ripe & dried fruit, marzipan, gingerbread and citrus fruits. Flavours of hazelnut, nougat, barley sugar, jellied and citrus fruits, almonds, brioche and honey.Krug Grande Cuvée lends itself to a plethora of culinary combinations, from the simplest to the most sophisticated, from an extra mature parmesan to a dish of turbot à la truffle.",
    "price": 12499500.0,
    "promotedPrice": 12489500.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Guidalberto-by-Sassicaia-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 56,
    "name": "dom perignon",
    "description": "Dom Pérignon (1638–1715) was a monk and cellar master at the Benedictine abbey in Hautvillers. He pioneered a number of winemaking techniques around 1670—being the first to blend grapes in such a way as to improve the quality of wines, balance one element with another in order to make a better whole, and deal with a number of their imperfections; perfecting the art of producing clear white wines from black grapes by clever manipulation of the presses.Dom Perignon has an intense, full and radiant bouquet with notes of honeysuckle, orange coloured fruits and hints of iodine sensations. The creamy chewiness characterizing the vintage is channelled in a direction that is edgy yet embracing with a wave of aromatic persistence. Smoky, biting and full energy finish balances it all out.The Dom Perignon pairs very well with sushi, scallops, oysters, white fish, white meat.",
    "price": 11999400.0,
    "promotedPrice": 11979400.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Kaiken-Reserva-malbec-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 57,
    "name": "bollinger special cuvee brut",
    "description": "To the eye: A golden colour, distinctive of black grape varieties; very ne bubbles. To the nose: A beautiful aromatic complexity; ripe fruit and spicy aromas; hints of roasted apples, apple compote and peaches. On the palate: A subtle combination of structure, length and vivacity; bubbles like velvet; pear, brioche and spicy aromas, notes of fresh walnut.This wine goes very well with any fish, especially sushi and sashimi. Seafood: shrimp, prawn, crayfish, grilled lobster. Poultry and white meat. Parmesan, good cured ham.",
    "price": 2579300.0,
    "promotedPrice": 2549300.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Kaiken-Ultra-malbec-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 58,
    "name": "bollinger rose",
    "description": "To the eye: bronze tones combined with the intense depth of a great red wine. To the nose: the nobility of red berries: hints of red currant, cherry and wild strawberry;a spicy touch, not unlike Special Cuvée. To the palate: a subtle combination of structure, length and vivacity, with a tannic finish due to the adjunction of red wine; bubbles as fine as velvet; flavours of wild berries.Cellar aged for more than twice the time required by the appellation.it pairs well with crayfish, lobster, one-side cooked salmon. Japanese cuisine or not-so-spicy Asian cuisine.",
    "price": 3119200.0,
    "promotedPrice": 3079200.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Lapostolle-Cabernet-Sauvignon-1-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 63,
    "name": "veuve clicquot brut",
    "description": "A Champagne House is eventually judged on the quality of its Brut Non Vintage. It is in the making of such a wine that the true Art of Champagne blending reveals itself. This is an art in which the House of Veuve Clicquot excels. Our Brut Yellow Label reflects the superb vineyards we own and the consistent nature of our House style.The predominance of Pinot Noir provides the structure that is so typically Clicquot, while a touch of Pinot Meunier rounds out the blend. Chardonnay adds the elegance and finesse essential in a perfectly balanced wine.",
    "price": 2339700.0,
    "promotedPrice": 2339700.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Clos-du-Val-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 31,
    "name": "prosecco liquid gold classic",
    "description": "Selected and healthy grapes; soft pressing and 10-day test winemaking in steel tanks. After the second fermentation at controlled temperature in pressurised vats using the Charmat method, the wine is filtered and decanted with isobaric technique before being bottled.Pale straw yellow with light lime green highlights. Pleasant, light, fine, delicate and long-lasting, fruity, with characteristic bouquet of Golden Delicious apples. Velvety, fresh, fruity and lively, slight and smooth, with a fine perlage, full-bodied, harmonic, excellent acidity.A classic Venetian aperitif, ideal with all meatbased starters, sausages, seafood salad and fish and shellfi sh pasta and rice courses. Perfect with white meats, grilled, boiled or fried fish with polenta.",
    "price": 889900.0,
    "promotedPrice": 849900.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/28-Lapostolle-Merlot-2014-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 17,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 29,
    "name": "cotes de provence, villa garrel",
    "description": "In the 16th century, the Villa Garrel was part of the former fief of Piegros. Today, Château de l’Aumérade Cru Classé is the jewel of the Fabre properties. Completely renovated, it now houses the head office of Fabre en Provence. The initials HF, engraved in one of the stones of the bastide, date from the Emperor Napoleon III (1868).Today, the vintners have the most modern equipment available with which to work, and craft an array of outstanding wines — including one for which Provence is perhaps best known: a fresh and juicy rosé.Crafted from three grape varieties — Grenache, Cinsault and Syrah — the 2018 Villa Garrel Rosé is a delightful wine with strawberry and papaya flavors that cascade into a long and creamy finish. It’s a wonderful wine for sipping on a hot summer day, or makes a great companion to summer salads.Pale pink, fruit-forward and refreshing rosé, crafted from Grenache, Cinsault and Syrah grapes. The nose is dominated by intense aromas of orange peel, white peach, strawberry and red cherry. This light and crisp rosé can complement a meal perfectly or be delightful on its own. Pairs well with light appetizers or spicy tapas.",
    "price": 889100.0,
    "promotedPrice": 869100.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/67-Ornellaia-Le-Serre-Nuove-dellOrnellaia-2013-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 18,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },

  {
    "id": 33,
    "name": "terrazas reserva malbec",
    "description": "Bright red color with purple shades. Intense floral and fruity notes. Presence of violets, ripe black cherry and plum aromas. ReIts sweet and juicy mouthfeel delivers finesse, delicate tannins and an elegant finish of black fruits. veals a toasty and spicy character of black pepper and chocolate.Pair with Tuna Carpaccio and Red Fruits Vinaigrette, Tenderloin served with Mediterranean Ratatouille and Moist Semisweet Chocolate Cake over Mascarpone and Red Fruits Ice Cream.",
    "price": 1589700.0,
    "promotedPrice": 1529700.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/69-AMARONE-DELLA-VALPOLICELLA-TOMMASI-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 34,
    "name": "terrazas reserva cabernet",
    "description": "Intense garnet red. Predominance of spicy notes of thyme and green pepper in harmony with an intense black fruit and figs background. A gentle and full wine. In the mouth, it reveals a precise and long finish.Pair with slow cooked lamb with spicy sauce and fresh salad or mashed potatoes.Wine Spectator – “A broad-textured red, with mocha notes to the roasted plum and dark cherry flavors. Dried mint and sage details show midpalate. The finish lingers with plenty of dark chocolate accents.”",
    "price": 1133600.0,
    "promotedPrice": 1063600.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/63-BANFI-ASKA-BOLGHERI-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 35,
    "name": "solaia",
    "description": "An intense ruby red in color with purple highlights, the nose of the wine is dominated by varietal notes of excellent freshness and an elegant intensity. The 2012 Solaia has a classic style and is characterized on the palate by the pleasurable harmony of flavors created by a fine balance between acidity and tannins and high level fruit which lasts from the initial impact through to the lengthy finish and aftertaste. A grand personality and a great persistence make the finish exceptionally complex and vibrant.Pairs well with grilled chicken, veal medallions, lamb in a red wine sauce, roasted pork loin, grilled tuna with a pepper crust.",
    "price": 11399500.0,
    "promotedPrice": 11319500.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/73-MARCHESI-ANTINORI-“SOLAIA”-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 36,
    "name": "penfolds bin 8",
    "description": "Bin 8 has been crafted in the traditional Penfolds style. Ripe, balanced fruit fl avours are supported by softly integrated oak resulting in an impressive, smooth red wine. It was introduced in response to a heightened interest in Cabernet Shiraz blends – a classic Australian wine style that caught the attention of the international wine media. Mulberry and plum fruits immediately ascend. Violet and iris fl orals sit atop vanilla and fermented tea-leaf aromatics. Scents of smoky/sweet roast-beef scrapings disguise shy oak.Suggested food pairing: Caramelised lamb, pickled tongue and smoked green chilli.",
    "price": 1799400.0,
    "promotedPrice": 1799400.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/51-PENFOLDS-BIN-8-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 37,
    "name": "penfolds bin 407",
    "description": "Inspired by Bin 707, Bin 407 offers varietal definition and approachability, yet still with structure and depth of flavour. Textbook Cabernet Sauvignon, the varietally expressive Bin 407 highlights the rewards of Penfolds multi-region, multi-vineyard blending, with a core of ripe fruit supported by sensitive use of French and American oak.One of Australia’s oldest wineries, Penfolds was founded in Adelaide in 1844 by Christopher Rawson Penfold. Renowned for its iconic range of red wines including the world-famous ‘Grange’ though their range extends to many much more affordable wines too!",
    "price": 3899300.0,
    "promotedPrice": 3889300.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Penfolds-Bin-407-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 38,
    "name": "parallele 45, jaboulet",
    "description": "This Domaine Paul Jaboulet Côtes du Rhône takes its name from the 45th North parallel which runs two kilometres from the cellars of Maison Paul Jaboulet. Their wine has had this name since the beginning of the 1950s. Elegant and aromatic Grenache blend, with red fruits blended with spices. Well-structured on rounded tannins, with a final spicy note.",
    "price": 833200.0,
    "promotedPrice": 813200.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/23-Catena-Alta-Malbec-2012-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 39,
    "name": "overture by opus one",
    "description": "The 2013 Opus One offers splendid aromas of blueberry, cassis, and blackberries with highlights of rose, anise and baking spices. A creamy entry gives way to layers of complexity which unfold in the mid-palate with velvety tannins enrobing a center of concentrated black-fruit with juicy freshness. Elegantly balanced, the acidity and core structure deliver a persistent finish with hints of dark chocolate. The 2013 Opus One promises enjoyment for decades to come.",
    "price": 7739100.0,
    "promotedPrice": 7709100.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Catena-Cabernet-Sauvignon-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 40,
    "name": "torbreck old vine",
    "description": "The 2013 Steading has a vibrant, purity of fruit, mid palate concentration and tannin profile making it an exemplary wine. Barossa cultivars of old vine Grenache, Shiraz & Mataro. Vibrant aromas of dark cherry, blackberry, and star anise all unfold to reveal an impressive array of underlying fruit flavours.Dense, succulent dark fruits with layers of liquorice, plum, black olive, earth, white pepper and Asian spice. These complex yet elegant flavours are all neatly interwoven with a perfect balance of acidity and supple, silky tannins.",
    "price": 960000.0,
    "promotedPrice": -1.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/5-CATENA-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 41,
    "name": "ornellaia",
    "description": "“What appeared to be a disadvantage for the 2013 vintage – late budding and flowering – proved to be a major advantage thanks to a warm summer and month of September offering textbook conditions for harvesting, with cool temperatures but a prevalence of sunny weather. This resulted in slow but complete ripening with great balance and a delightful aromatic quality, which we like to define as “Elegance”. Ornellaia 2013, with its dense, vibrant colour, has a nose of splendid aromatic complexity built around a limpid and brilliant fruitiness, underscored by refined spicy and balsamic notes. The mouth develops vibrant and complex fruity nuances framed by a dense, slender structure with tannins that attain a rare harmony between firmness and fleshiness, concluding with a long balanced and fresh finish.”",
    "price": 5699900.0,
    "promotedPrice": 5649900.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/67-Ornellaia-Le-Serre-Nuove-dellOrnellaia-2013-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 42,
    "name": "napanook dominus",
    "description": "Dominus, with its remarkably complex nose, is an utterly seductive wine. It displays red and black fruits and an ethereal aroma of deep cherry, warm citrus and marzipan. Finely polished tannins on a beautiful, weightless finish are accompanied by great depth and length.",
    "price": 3899800.0,
    "promotedPrice": 3839800.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Chateau-dArmailhac-Rothschild-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 43,
    "name": "muga",
    "description": "A wine with medium-high depth of color — black-cherry red with garnet hues. First, red-fruit notes appear on the nose, with hints of fennel and scrubby heathland, all nicely balanced by smokey aromas from the time spent in medium-toasted wood. Underlying hints of vanilla come through with coffee notes. On the palate, there is a full mouth-feel with slightly mentholated nuances and white chocolate. The vanilla reappears and the red-berry fruit aromas found on the nose persist, with an elegant acidity which makes the aftertaste long.This wine can be paired with veal, Iberian pork charcuterie and some types of casseroles (stew).This wine is ruby-red with glints of brick-red and a medium-high depth of colour. Dense legs which provide you with a sequence of patterns around the sides of the glass.Initially you can find notes of red fruit aromas such as blackberries and reminders of spices. This is all well balanced by smoked aromas from its time in wood which had received a light-to-medium toasting. A subtle vanilla pod aroma coming through with roast coffee nuances.A smooth, mellow attack, with tannins wrapping the sides of the mouth with hints of menthol. In the finish the interesting lingering persistence is worthy of note.Food pairing:You can pair this wine with veal, Iberian ham and charcuterie and some kinds of stews and hotpots.",
    "price": 1073700.0,
    "promotedPrice": 1003700.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Muga-reserva-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 44,
    "name": "moulins de citran",
    "description": "Cornas has a dark full color with a purple edge. The aroma is intense with black fruit, pepper, violets and roasted chocolate. Cornas tastes powerful and dark with spicy fruit that clearly refers to the granite surface. The wine has ripe and round tannins and a stunning mineral final.Serve at room temperature, when young with grilled meat, delicious after 5 years with game and aged cheeses.This small appellation is located on the right bank of the Rhone Valley with granite soils at an altitude of 300m. A cold maceration removes all the aromas and the deep color from the fruit. In all, maceration and fermentation takes 20 days with pumping and pigeage to the end. The wine ages in 1 and 2 year old barrels for 15 months.",
    "price": 1553600.0,
    "promotedPrice": 1473600.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/81-Paul-Jaboulet-Aine-Châteauneuf-du-Pape-Les-Cèdres-Rouge-2006-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 45,
    "name": "montes purple angel",
    "description": "The grapes for Purple Angel come from Montes’ own vineyards in Apalta and Marchigüe, arguably two of the finest sites in the Colchagua Valley. In Apalta, vines are planted on 45° slopes, providing good exposure to achieve ripeness. Cool ocean breezes and low nighttime temperatures moderate this warm area, permitting slow development and retention of varietal aromas and acidity. Marchigüe is slightly cooler because of its closer proximity to the ocean. Conditions are dry, reducing the threat of fungal disease and resulting in consistently healthy harvests. All grapes were hand harvested.Purple Angel displays the rich flavours typical of Carménère. The addition of Petit Verdot gives spice, colour, structure and acidity. Deep ruby red in colour, the wine has alluring red and blackberry notes on the nose. The palate is densely concentrated, with spice and mocha lingering on the finish.",
    "price": 3299500.0,
    "promotedPrice": 3299500.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Montes-Purple-Angel-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 46,
    "name": "montes alpha m",
    "description": "Intense dark red colour. Very elegant with very dense and velvety, supple tannins. The wine has an harmonious structure, combined with a generous fruit expression and a very distinguished character showing aromas of red fruits, cassis and a touch of cedar and cinnamon. In the mouth the wine has delightful notes of vanilla and coffee. The 5% of Petit Verdot adds an extra element of complexity. Mouth filling and long and well-defined through the finish. The structure of this wine will keep it for over 20 years.Highly recommended with baked turkey, rib eye steak, sherry kidneys, duck confit.",
    "price": 3599400.0,
    "promotedPrice": 3589400.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/39-Montes-Alpha-M-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 47,
    "name": "montes alpha",
    "description": "A lively red color is the first clue that the wine before us is very fresh. Its aromatic potency is very well harmonized with its complexity. There’s a predominance of red berries, jam, blackcurrant liqueur (creme de cassis}, and a juicy sensation of crushed strawberries. Eight months in contact with French oak lend it a certain degree of seriousness, along with a bit of vanilla, smoke, cigar box, and sweet spices. Good balance on the palate with properly rounded tannins that enable this Cabernet Sauvignon to linger long on the palate.Highly recommended with braised beef with French fries, steak and eggs, paella, cannelloni, and lasagna.Wine Spectator – “There’s minerally freshness to the ripe dark plum, blackberry and cherry flavors, with peppery hints. Well-structured and crisp midpalate, featuring Asian spice and black fig notes on the finish. Drink now through 2020.”",
    "price": 1073300.0,
    "promotedPrice": 1053300.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/34-MONTES-ALPHA-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 48,
    "name": "migration",
    "description": "As with any great wine, Alto will show at its best when served with the finest foods that are simply prepared. A filet mignon or Chateaubriand grilled medium-rare are perfect, as are lechazo, roast suckling baby lamb or grilled chuletas de cordero, lamb chops.",
    "price": 1979200.0,
    "promotedPrice": 1949200.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Clos-du-Val-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 49,
    "name": "merryvale",
    "description": "Drawn from three top Napa vineyards; Kenefick Ranch, Salvador and Rancho Chimiles, our Cabernet Sauvignon is handpicked and undergoes a triple sorting upon arrival at the winery. The grapes then undergo an extended maceration and a long, cool fermentation for increased flavor, color and aroma. Aged in 50% new French oak barrels, the wine matures for 22 months before being deemed ready for release. Our Napa Cabernet bottling is always blended with other Bordeaux varietals for their added aromatic and balanced tannin contributions.A quintessential Napa Cabernet, this wine is rich and dark in the glass. Aromas of blackberry and faint dried herb waft up from the rim towards you. Upon tasting, the wine has a broad and pleasant entry, moving to a focused and weighty mid palate with notes of cassis, toast and graphite. A lengthy finish shows well proportioned tannin that will gain even more complexity as time passes. With proper cellaring, this wine will drink beautifully for the next 15 years.",
    "price": 3473100.0,
    "promotedPrice": 3433100.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Merryvale-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 50,
    "name": "massetto",
    "description": "Tenuta dell’Ornellaia Masseto Merlot is a dry red wine produced in Toscana, Italy. The wine boasts a vibrant, perfectly balanced and rounded taste, featuring notes of fruit, minerals, espresso, chocolate with spices and licorice. The finish is long and satisfying. The aroma is elegant and complex, with an air of sophistication. This exquisite wine makes an excellent accompaniment for meat and pasta dishes.",
    "price": 18000000.0,
    "promotedPrice": -1.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/43-VN-DECOY-cabernet-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 51,
    "name": "opus one",
    "description": "The 2013 Opus One offers splendid aromas of blueberry, cassis, and blackberries with highlights of rose, anise and baking spices. A creamy entry gives way to layers of complexity which unfold in the mid-palate with velvety tannins enrobing a center of concentrated black-fruit with juicy freshness. Elegantly balanced, the acidity and core structure deliver a persistent finish with hints of dark chocolate. The 2013 Opus One promises enjoyment for decades to come.",
    "price": 16799900.0,
    "promotedPrice": 16739900.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/46-Opus-One-2013-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  },
  {
    "id": 52,
    "name": "marchesi di barolo, coste di rose",
    "description": "Barbera is typically marked by red cherry, raspberry, and blackberry flavors backed by a signature zingy acidity and smooth tannins. More complex examples can include notes of cocoa, savory spice, anise, and nutmeg. In warmer New World climates, Barbera is all about the fruit, sometimes leaning towards over-ripe or dried fruit flavors that can give an impression of sweetness to the wine. Old World Barbera can develop intriguing notes of graphite, smoke, lavender, and violet.Barbera’s prominent acidity makes it a natural match with tomato-based dishes, therefore making it an easy pairing with a wide array of Italian cuisine. It works just as well with lighter red meat dishes, hamburgers, or barbecue.",
    "price": 2999800.0,
    "promotedPrice": 2929800.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Don-Melchor-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 20,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "areaId": 8
  }
]
export default Products;