const Products = [
  {
    "id": 65,
    "name": "ARGENTINIAN BEEF FILET SOUP",
    "description": "",
    "price": 290000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 0,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 66,
    "name": "LOBSTER AND CRAB MEAT SOUP",
    "description": "",
    "price": 290000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 0,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 188,
    "name": "ARGENTINIAN BEEF FILET SOUP",
    "description": "",
    "price": 290000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 0,
    "category": 0,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 189,
    "name": "LOBSTER AND CRAB MEAT SOUP",
    "description": "",
    "price": 290000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 0,
    "category": 0,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 67,
    "name": "BEEF EMPANADA",
    "description": "",
    "price": 180000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 68,
    "name": "CHORIZO BEEF",
    "description": "Homemade argentinian spiced sausage",
    "price": 210000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 69,
    "name": "SALCHICHA",
    "description": "Homemade argentinian spicy sausage",
    "price": 210000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 70,
    "name": "PROVOLETA",
    "description": "Grilled provolone cheese, tomato with a hint of oregano",
    "price": 280000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 71,
    "name": "TACOS",
    "description": "Lean homemade minced beef, crispy taco shells, avocado, tomato, chives, coriander (2PCS PER SERVING)",
    "price": 290000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 187,
    "name": "GREEN ASPARAGUS SOUP",
    "description": "A\nB\nC",
    "price": 290000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 190,
    "name": "BEEF EMPANADA",
    "description": "",
    "price": 180000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 191,
    "name": "CHORIZO BEEF",
    "description": "Homemade argentinian spiced sausage",
    "price": 210000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 192,
    "name": "SALCHICHA",
    "description": "Homemade argentinian spicy sausage",
    "price": 210000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 193,
    "name": "PROVOLETA",
    "description": "Grilled provolone cheese, tomato with a hint of oregano",
    "price": 280000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 194,
    "name": "TACOS",
    "description": "Lean homemade minced beef, crispy taco shells, avocado, tomato, chives, coriander (2PCS PER SERVING)",
    "price": 290000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/40-Lapostolle-Clos-Apalta-2011-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 2,
    "category": 0,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 88,
    "name": "FILET STEAK",
    "description": "",
    "price": 1937000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/el-gaucho-argentinian-steakhouse-restaurant-wagyu-tomahawk-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 122,
    "name": "Add On - Foie Gras",
    "description": "The USDA Prime is the highest grade of beef in the USA and properly aged in our cold storage for additional 21 to 28 days to fully develop the flavour and tenderness for that melt in your mouth and consistent quality experience. Taken from the smaller end of the tenderloin and located between the sirloin and rib, hand-cut and hand-trimmed by the El Gaucho butchers, the filet steak is a feast for the eye and the mouth. The Castello D’Albola Chianti Classico DOCG 2011 from Tuscany pairs nicely with a filet. It is firm and taut, with a core of cherry and berry flavors, accented by underbrush tobacco and iron notes, balanced with a mineral aftertaste. Perfect for dishes of the traditional Chianti cuisine, as well as for grilled meats and mature cheeses.",
    "price": 622500.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/El-Gaucho-Argentinian-Steakhouse-Restaurant-Filet-Platinum-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 123,
    "name": "NEW YORK STRIPLOIN",
    "description": "The USDA Prime is the highest grade of beef in the USA and properly aged in our cold storage for additional 21 to 28 days to fully develop the flavour and tenderness for that melt in your mouth and consistent quality experience. Taken from the smaller end of the tenderloin and located between the sirloin and rib, hand-cut and hand-trimmed by the El Gaucho butchers, the filet steak is a feast for the eye and the mouth. The Castello D’Albola Chianti Classico DOCG 2011 from Tuscany pairs nicely with a filet. It is firm and taut, with a core of cherry and berry flavors, accented by underbrush tobacco and iron notes, balanced with a mineral aftertaste. Perfect for dishes of the traditional Chianti cuisine, as well as for grilled meats and mature cheeses.",
    "price": 497500.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/El-Gaucho-Argentinian-Steakhouse-Restaurant-Filet-USDA-Prime-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 211,
    "name": "FILET STEAK",
    "description": "",
    "price": 1937000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/el-gaucho-argentinian-steakhouse-restaurant-wagyu-tomahawk-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 213,
    "name": "NEW YORK STRIPLOIN",
    "description": "The USDA Prime is the highest grade of beef in the USA and properly aged in our cold storage for additional 21 to 28 days to fully develop the flavour and tenderness for that melt in your mouth and consistent quality experience. Taken from the smaller end of the tenderloin and located between the sirloin and rib, hand-cut and hand-trimmed by the El Gaucho butchers, the filet steak is a feast for the eye and the mouth. The Castello D’Albola Chianti Classico DOCG 2011 from Tuscany pairs nicely with a filet. It is firm and taut, with a core of cherry and berry flavors, accented by underbrush tobacco and iron notes, balanced with a mineral aftertaste. Perfect for dishes of the traditional Chianti cuisine, as well as for grilled meats and mature cheeses.",
    "price": 497500.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/El-Gaucho-Argentinian-Steakhouse-Restaurant-Filet-USDA-Prime-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 244,
    "name": "Add On - Foie Gras",
    "description": "The USDA Prime is the highest grade of beef in the USA and properly aged in our cold storage for additional 21 to 28 days to fully develop the flavour and tenderness for that melt in your mouth and consistent quality experience. Taken from the smaller end of the tenderloin and located between the sirloin and rib, hand-cut and hand-trimmed by the El Gaucho butchers, the filet steak is a feast for the eye and the mouth. The Castello D’Albola Chianti Classico DOCG 2011 from Tuscany pairs nicely with a filet. It is firm and taut, with a core of cherry and berry flavors, accented by underbrush tobacco and iron notes, balanced with a mineral aftertaste. Perfect for dishes of the traditional Chianti cuisine, as well as for grilled meats and mature cheeses.",
    "price": 622500.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/El-Gaucho-Argentinian-Steakhouse-Restaurant-Filet-Platinum-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 8,
    "category": 2,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 28,
    "name": "taittinger brut reserve",
    "description": "Brut Réserve Taittinger is one of the last great Champagne Houses to remain independent and is owned and actively managed by the family named on the label. The family are guardians of Taittinger’s style quality and integrity. The hallmark of their fine Champagnes is the high proportion of Chardonnay used in their winemaking which is key, in the Champagne region, for producing wines of great elegance and finesse. Additionally, with its vineyard ownership of 288 ha (one of the largest in Champagne}, Taittinger can guarantee a flawless signature, and wines heralded worldwide for their consistent quality. Our signature cuvée, Taittinger Brut Réserve, is assembled from more than 35 crus and incorporates 40% Chardonnay – this high level is seldom offered in a non-vintage Champagne. Distinguished by a delicate nose marked by subtle brioche notes, it has a palate of considerable depth and balance with hints of honey and fresh fruit with a long, fresh finish.",
    "price": 2100000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/73-MARCHESI-ANTINORI-“SOLAIA”-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 55,
    "name": "krug grande cuvee",
    "description": "Behind every precious drop of Krug stands the dream of a visionary. One man who, long before others, understood that the essence of Champagne is pleasure. So, over 170 years ago, Joseph Krug broke with convention to follow his vision. To create the most generous expression of Champagne every year, regardless of climatic unpredictability.Joseph’s bold experiment proved a triumph and he succeeded in creating Champagne like never before. And like no other Champagne House since. To this day, the House of Krug lives and breathes his enduring philosophy, creating only prestige Champagnes since 1843. Deep golden colour and fine, vivacious bubbles, predicting fullness and elegance. Aromas of flowers in bloom, ripe & dried fruit, marzipan, gingerbread and citrus fruits. Flavours of hazelnut, nougat, barley sugar, jellied and citrus fruits, almonds, brioche and honey.Krug Grande Cuvée lends itself to a plethora of culinary combinations, from the simplest to the most sophisticated, from an extra mature parmesan to a dish of turbot à la truffle.",
    "price": 12500000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Guidalberto-by-Sassicaia-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 56,
    "name": "dom perignon",
    "description": "Dom Pérignon (1638–1715) was a monk and cellar master at the Benedictine abbey in Hautvillers. He pioneered a number of winemaking techniques around 1670—being the first to blend grapes in such a way as to improve the quality of wines, balance one element with another in order to make a better whole, and deal with a number of their imperfections; perfecting the art of producing clear white wines from black grapes by clever manipulation of the presses.Dom Perignon has an intense, full and radiant bouquet with notes of honeysuckle, orange coloured fruits and hints of iodine sensations. The creamy chewiness characterizing the vintage is channelled in a direction that is edgy yet embracing with a wave of aromatic persistence. Smoky, biting and full energy finish balances it all out.The Dom Perignon pairs very well with sushi, scallops, oysters, white fish, white meat.",
    "price": 12000000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Kaiken-Reserva-malbec-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 57,
    "name": "bollinger special cuvee brut",
    "description": "To the eye: A golden colour, distinctive of black grape varieties; very ne bubbles. To the nose: A beautiful aromatic complexity; ripe fruit and spicy aromas; hints of roasted apples, apple compote and peaches. On the palate: A subtle combination of structure, length and vivacity; bubbles like velvet; pear, brioche and spicy aromas, notes of fresh walnut.This wine goes very well with any fish, especially sushi and sashimi. Seafood: shrimp, prawn, crayfish, grilled lobster. Poultry and white meat. Parmesan, good cured ham.",
    "price": 2580000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Kaiken-Ultra-malbec-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 58,
    "name": "bollinger rose",
    "description": "To the eye: bronze tones combined with the intense depth of a great red wine. To the nose: the nobility of red berries: hints of red currant, cherry and wild strawberry;a spicy touch, not unlike Special Cuvée. To the palate: a subtle combination of structure, length and vivacity, with a tannic finish due to the adjunction of red wine; bubbles as fine as velvet; flavours of wild berries.Cellar aged for more than twice the time required by the appellation.it pairs well with crayfish, lobster, one-side cooked salmon. Japanese cuisine or not-so-spicy Asian cuisine.",
    "price": 3120000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Lapostolle-Cabernet-Sauvignon-1-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 63,
    "name": "veuve clicquot brut",
    "description": "A Champagne House is eventually judged on the quality of its Brut Non Vintage. It is in the making of such a wine that the true Art of Champagne blending reveals itself. This is an art in which the House of Veuve Clicquot excels. Our Brut Yellow Label reflects the superb vineyards we own and the consistent nature of our House style.The predominance of Pinot Noir provides the structure that is so typically Clicquot, while a touch of Pinot Meunier rounds out the blend. Chardonnay adds the elegance and finesse essential in a perfectly balanced wine.",
    "price": 2340000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Clos-du-Val-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 138,
    "name": "taittinger brut reserve",
    "description": "Brut Réserve Taittinger is one of the last great Champagne Houses to remain independent and is owned and actively managed by the family named on the label. The family are guardians of Taittinger’s style quality and integrity. The hallmark of their fine Champagnes is the high proportion of Chardonnay used in their winemaking which is key, in the Champagne region, for producing wines of great elegance and finesse. Additionally, with its vineyard ownership of 288 ha (one of the largest in Champagne}, Taittinger can guarantee a flawless signature, and wines heralded worldwide for their consistent quality. Our signature cuvée, Taittinger Brut Réserve, is assembled from more than 35 crus and incorporates 40% Chardonnay – this high level is seldom offered in a non-vintage Champagne. Distinguished by a delicate nose marked by subtle brioche notes, it has a palate of considerable depth and balance with hints of honey and fresh fruit with a long, fresh finish.",
    "price": 2100000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/73-MARCHESI-ANTINORI-“SOLAIA”-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },


  {
    "id": 186,
    "name": "veuve clicquot brut",
    "description": "A Champagne House is eventually judged on the quality of its Brut Non Vintage. It is in the making of such a wine that the true Art of Champagne blending reveals itself. This is an art in which the House of Veuve Clicquot excels. Our Brut Yellow Label reflects the superb vineyards we own and the consistent nature of our House style.The predominance of Pinot Noir provides the structure that is so typically Clicquot, while a touch of Pinot Meunier rounds out the blend. Chardonnay adds the elegance and finesse essential in a perfectly balanced wine.",
    "price": 2340000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Clos-du-Val-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 31,
    "name": "prosecco liquid gold classic",
    "description": "Selected and healthy grapes; soft pressing and 10-day test winemaking in steel tanks. After the second fermentation at controlled temperature in pressurised vats using the Charmat method, the wine is filtered and decanted with isobaric technique before being bottled.Pale straw yellow with light lime green highlights. Pleasant, light, fine, delicate and long-lasting, fruity, with characteristic bouquet of Golden Delicious apples. Velvety, fresh, fruity and lively, slight and smooth, with a fine perlage, full-bodied, harmonic, excellent acidity.A classic Venetian aperitif, ideal with all meatbased starters, sausages, seafood salad and fish and shellfi sh pasta and rice courses. Perfect with white meats, grilled, boiled or fried fish with polenta.",
    "price": 890000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/28-Lapostolle-Merlot-2014-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 17,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 152,
    "name": "prosecco liquid gold classic",
    "description": "Selected and healthy grapes; soft pressing and 10-day test winemaking in steel tanks. After the second fermentation at controlled temperature in pressurised vats using the Charmat method, the wine is filtered and decanted with isobaric technique before being bottled.Pale straw yellow with light lime green highlights. Pleasant, light, fine, delicate and long-lasting, fruity, with characteristic bouquet of Golden Delicious apples. Velvety, fresh, fruity and lively, slight and smooth, with a fine perlage, full-bodied, harmonic, excellent acidity.A classic Venetian aperitif, ideal with all meatbased starters, sausages, seafood salad and fish and shellfi sh pasta and rice courses. Perfect with white meats, grilled, boiled or fried fish with polenta.",
    "price": 890000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/28-Lapostolle-Merlot-2014-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 17,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 29,
    "name": "cotes de provence, villa garrel",
    "description": "In the 16th century, the Villa Garrel was part of the former fief of Piegros. Today, Château de l’Aumérade Cru Classé is the jewel of the Fabre properties. Completely renovated, it now houses the head office of Fabre en Provence. The initials HF, engraved in one of the stones of the bastide, date from the Emperor Napoleon III (1868).Today, the vintners have the most modern equipment available with which to work, and craft an array of outstanding wines — including one for which Provence is perhaps best known: a fresh and juicy rosé.Crafted from three grape varieties — Grenache, Cinsault and Syrah — the 2018 Villa Garrel Rosé is a delightful wine with strawberry and papaya flavors that cascade into a long and creamy finish. It’s a wonderful wine for sipping on a hot summer day, or makes a great companion to summer salads.Pale pink, fruit-forward and refreshing rosé, crafted from Grenache, Cinsault and Syrah grapes. The nose is dominated by intense aromas of orange peel, white peach, strawberry and red cherry. This light and crisp rosé can complement a meal perfectly or be delightful on its own. Pairs well with light appetizers or spicy tapas.",
    "price": 890000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/67-Ornellaia-Le-Serre-Nuove-dellOrnellaia-2013-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 18,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 30,
    "name": "whispering angel, chateau desclans",
    "description": "Strikingly pale pink in color, the aromas are fresh and fruity. On the palate, it is bone dry through the finish. The name really suits the delicate nature of this wine.",
    "price": 1254000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/35-Lapostolle-Cuvee-Alexandre-Merlot-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 18,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 136,
    "name": "cotes de provence, villa garrel",
    "description": "In the 16th century, the Villa Garrel was part of the former fief of Piegros. Today, Château de l’Aumérade Cru Classé is the jewel of the Fabre properties. Completely renovated, it now houses the head office of Fabre en Provence. The initials HF, engraved in one of the stones of the bastide, date from the Emperor Napoleon III (1868).Today, the vintners have the most modern equipment available with which to work, and craft an array of outstanding wines — including one for which Provence is perhaps best known: a fresh and juicy rosé.Crafted from three grape varieties — Grenache, Cinsault and Syrah — the 2018 Villa Garrel Rosé is a delightful wine with strawberry and papaya flavors that cascade into a long and creamy finish. It’s a wonderful wine for sipping on a hot summer day, or makes a great companion to summer salads.Pale pink, fruit-forward and refreshing rosé, crafted from Grenache, Cinsault and Syrah grapes. The nose is dominated by intense aromas of orange peel, white peach, strawberry and red cherry. This light and crisp rosé can complement a meal perfectly or be delightful on its own. Pairs well with light appetizers or spicy tapas.",
    "price": 890000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/67-Ornellaia-Le-Serre-Nuove-dellOrnellaia-2013-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 18,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 151,
    "name": "whispering angel, chateau desclans",
    "description": "Strikingly pale pink in color, the aromas are fresh and fruity. On the palate, it is bone dry through the finish. The name really suits the delicate nature of this wine.",
    "price": 1254000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/35-Lapostolle-Cuvee-Alexandre-Merlot-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 18,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 28,
    "name": "taittinger brut reserve",
    "description": "Brut Réserve Taittinger is one of the last great Champagne Houses to remain independent and is owned and actively managed by the family named on the label. The family are guardians of Taittinger’s style quality and integrity. The hallmark of their fine Champagnes is the high proportion of Chardonnay used in their winemaking which is key, in the Champagne region, for producing wines of great elegance and finesse. Additionally, with its vineyard ownership of 288 ha (one of the largest in Champagne}, Taittinger can guarantee a flawless signature, and wines heralded worldwide for their consistent quality. Our signature cuvée, Taittinger Brut Réserve, is assembled from more than 35 crus and incorporates 40% Chardonnay – this high level is seldom offered in a non-vintage Champagne. Distinguished by a delicate nose marked by subtle brioche notes, it has a palate of considerable depth and balance with hints of honey and fresh fruit with a long, fresh finish.",
    "price": 2100000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/73-MARCHESI-ANTINORI-“SOLAIA”-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 55,
    "name": "krug grande cuvee",
    "description": "Behind every precious drop of Krug stands the dream of a visionary. One man who, long before others, understood that the essence of Champagne is pleasure. So, over 170 years ago, Joseph Krug broke with convention to follow his vision. To create the most generous expression of Champagne every year, regardless of climatic unpredictability.Joseph’s bold experiment proved a triumph and he succeeded in creating Champagne like never before. And like no other Champagne House since. To this day, the House of Krug lives and breathes his enduring philosophy, creating only prestige Champagnes since 1843. Deep golden colour and fine, vivacious bubbles, predicting fullness and elegance. Aromas of flowers in bloom, ripe & dried fruit, marzipan, gingerbread and citrus fruits. Flavours of hazelnut, nougat, barley sugar, jellied and citrus fruits, almonds, brioche and honey.Krug Grande Cuvée lends itself to a plethora of culinary combinations, from the simplest to the most sophisticated, from an extra mature parmesan to a dish of turbot à la truffle.",
    "price": 12500000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Guidalberto-by-Sassicaia-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 56,
    "name": "dom perignon",
    "description": "Dom Pérignon (1638–1715) was a monk and cellar master at the Benedictine abbey in Hautvillers. He pioneered a number of winemaking techniques around 1670—being the first to blend grapes in such a way as to improve the quality of wines, balance one element with another in order to make a better whole, and deal with a number of their imperfections; perfecting the art of producing clear white wines from black grapes by clever manipulation of the presses.Dom Perignon has an intense, full and radiant bouquet with notes of honeysuckle, orange coloured fruits and hints of iodine sensations. The creamy chewiness characterizing the vintage is channelled in a direction that is edgy yet embracing with a wave of aromatic persistence. Smoky, biting and full energy finish balances it all out.The Dom Perignon pairs very well with sushi, scallops, oysters, white fish, white meat.",
    "price": 12000000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Kaiken-Reserva-malbec-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 57,
    "name": "bollinger special cuvee brut",
    "description": "To the eye: A golden colour, distinctive of black grape varieties; very ne bubbles. To the nose: A beautiful aromatic complexity; ripe fruit and spicy aromas; hints of roasted apples, apple compote and peaches. On the palate: A subtle combination of structure, length and vivacity; bubbles like velvet; pear, brioche and spicy aromas, notes of fresh walnut.This wine goes very well with any fish, especially sushi and sashimi. Seafood: shrimp, prawn, crayfish, grilled lobster. Poultry and white meat. Parmesan, good cured ham.",
    "price": 2580000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Kaiken-Ultra-malbec-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 58,
    "name": "bollinger rose",
    "description": "To the eye: bronze tones combined with the intense depth of a great red wine. To the nose: the nobility of red berries: hints of red currant, cherry and wild strawberry;a spicy touch, not unlike Special Cuvée. To the palate: a subtle combination of structure, length and vivacity, with a tannic finish due to the adjunction of red wine; bubbles as fine as velvet; flavours of wild berries.Cellar aged for more than twice the time required by the appellation.it pairs well with crayfish, lobster, one-side cooked salmon. Japanese cuisine or not-so-spicy Asian cuisine.",
    "price": 3120000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Lapostolle-Cabernet-Sauvignon-1-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 63,
    "name": "veuve clicquot brut",
    "description": "A Champagne House is eventually judged on the quality of its Brut Non Vintage. It is in the making of such a wine that the true Art of Champagne blending reveals itself. This is an art in which the House of Veuve Clicquot excels. Our Brut Yellow Label reflects the superb vineyards we own and the consistent nature of our House style.The predominance of Pinot Noir provides the structure that is so typically Clicquot, while a touch of Pinot Meunier rounds out the blend. Chardonnay adds the elegance and finesse essential in a perfectly balanced wine.",
    "price": 2340000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Clos-du-Val-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 8,
    "additions": [],
    "menu": {
      "id": 8,
      "areaName": "Đà Nẵng",
      "areaId": 8,
      "country": 0
    },
    "areaId": 8
  },
  {
    "id": 138,
    "name": "taittinger brut reserve",
    "description": "Brut Réserve Taittinger is one of the last great Champagne Houses to remain independent and is owned and actively managed by the family named on the label. The family are guardians of Taittinger’s style quality and integrity. The hallmark of their fine Champagnes is the high proportion of Chardonnay used in their winemaking which is key, in the Champagne region, for producing wines of great elegance and finesse. Additionally, with its vineyard ownership of 288 ha (one of the largest in Champagne}, Taittinger can guarantee a flawless signature, and wines heralded worldwide for their consistent quality. Our signature cuvée, Taittinger Brut Réserve, is assembled from more than 35 crus and incorporates 40% Chardonnay – this high level is seldom offered in a non-vintage Champagne. Distinguished by a delicate nose marked by subtle brioche notes, it has a palate of considerable depth and balance with hints of honey and fresh fruit with a long, fresh finish.",
    "price": 2100000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/73-MARCHESI-ANTINORI-“SOLAIA”-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 153,
    "name": "bollinger rose",
    "description": "To the eye: bronze tones combined with the intense depth of a great red wine. To the nose: the nobility of red berries: hints of red currant, cherry and wild strawberry;a spicy touch, not unlike Special Cuvée. To the palate: a subtle combination of structure, length and vivacity, with a tannic finish due to the adjunction of red wine; bubbles as fine as velvet; flavours of wild berries.Cellar aged for more than twice the time required by the appellation.it pairs well with crayfish, lobster, one-side cooked salmon. Japanese cuisine or not-so-spicy Asian cuisine.",
    "price": 3120000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Lapostolle-Cabernet-Sauvignon-1-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 178,
    "name": "krug grande cuvee",
    "description": "Behind every precious drop of Krug stands the dream of a visionary. One man who, long before others, understood that the essence of Champagne is pleasure. So, over 170 years ago, Joseph Krug broke with convention to follow his vision. To create the most generous expression of Champagne every year, regardless of climatic unpredictability.Joseph’s bold experiment proved a triumph and he succeeded in creating Champagne like never before. And like no other Champagne House since. To this day, the House of Krug lives and breathes his enduring philosophy, creating only prestige Champagnes since 1843. Deep golden colour and fine, vivacious bubbles, predicting fullness and elegance. Aromas of flowers in bloom, ripe & dried fruit, marzipan, gingerbread and citrus fruits. Flavours of hazelnut, nougat, barley sugar, jellied and citrus fruits, almonds, brioche and honey.Krug Grande Cuvée lends itself to a plethora of culinary combinations, from the simplest to the most sophisticated, from an extra mature parmesan to a dish of turbot à la truffle.",
    "price": 12500000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Guidalberto-by-Sassicaia-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 179,
    "name": "dom perignon",
    "description": "Dom Pérignon (1638–1715) was a monk and cellar master at the Benedictine abbey in Hautvillers. He pioneered a number of winemaking techniques around 1670—being the first to blend grapes in such a way as to improve the quality of wines, balance one element with another in order to make a better whole, and deal with a number of their imperfections; perfecting the art of producing clear white wines from black grapes by clever manipulation of the presses.Dom Perignon has an intense, full and radiant bouquet with notes of honeysuckle, orange coloured fruits and hints of iodine sensations. The creamy chewiness characterizing the vintage is channelled in a direction that is edgy yet embracing with a wave of aromatic persistence. Smoky, biting and full energy finish balances it all out.The Dom Perignon pairs very well with sushi, scallops, oysters, white fish, white meat.",
    "price": 12000000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Kaiken-Reserva-malbec-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 180,
    "name": "bollinger special cuvee brut",
    "description": "To the eye: A golden colour, distinctive of black grape varieties; very ne bubbles. To the nose: A beautiful aromatic complexity; ripe fruit and spicy aromas; hints of roasted apples, apple compote and peaches. On the palate: A subtle combination of structure, length and vivacity; bubbles like velvet; pear, brioche and spicy aromas, notes of fresh walnut.This wine goes very well with any fish, especially sushi and sashimi. Seafood: shrimp, prawn, crayfish, grilled lobster. Poultry and white meat. Parmesan, good cured ham.",
    "price": 2580000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Kaiken-Ultra-malbec-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  },
  {
    "id": 186,
    "name": "veuve clicquot brut",
    "description": "A Champagne House is eventually judged on the quality of its Brut Non Vintage. It is in the making of such a wine that the true Art of Champagne blending reveals itself. This is an art in which the House of Veuve Clicquot excels. Our Brut Yellow Label reflects the superb vineyards we own and the consistent nature of our House style.The predominance of Pinot Noir provides the structure that is so typically Clicquot, while a touch of Pinot Meunier rounds out the blend. Chardonnay adds the elegance and finesse essential in a perfectly balanced wine.",
    "price": 2340000.0,
    "imageUrl": "https://vn.elgaucho.asia/wp-content/uploads/2020/04/Clos-du-Val-100x100.jpg",
    "currency": null,
    "isAvailable": true,
    "priority": 0,
    "subCategory": 16,
    "category": 5,
    "menuId": 7,
    "additions": [],
    "menu": {
      "id": 7,
      "areaName": "Hồ Chí Minh",
      "areaId": 7,
      "country": 0
    },
    "areaId": 7
  }
]
export default Products;